apiVersion: skaffold/v2beta25
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: prabhkang/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "/src/**/*.ts"
            dest: .
    - image: prabhkang/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*ts"
            dest: .
    - image: prabhkang/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "/src/**/*.ts"
            dest: .
